### ISSUE TITLE
Azure Blob Example

### ISSUE THREAD

**Issue by thomasjgrady** [HDFGroup/h5pyd#109]
Is there an example or canonical way of using this package with azure blob storage? I am attempting to read slices of an hdf5 file to an Azure VM instance from Azure Blob storage. Preferably with normal access tokens as opposed to SAS tokens. I have a single hdf5 file `bar.h5` located in a container called `foo`. Thank you.

**Comment by jreadey** [comment]
The h5pyd package itself doesn't read from Azure blob storage, but you can used h5pyd with a HSDS server running on Azure.  Have you tried that?

**Comment by jreadey** [comment]
Closing this issue - please re-open if you still have questions.
