### ISSUE TITLE
Release?

### ISSUE THREAD

**Issue by jakirkham** [HDFGroup/h5pyd#11]
Seems there is mention of `pip install` as a mechanism of installation. Though I don't see it on PyPI and there are tags on the repo. Can a release be made?

**Comment by jreadey** [comment]
I was waiting to get h5pyd to a release-able state and then publish to a PyPI.
Is the pip install something you need immediately or can you manually build for now?

**Comment by grisaitis** [comment]
@jreadey I don't think it's absolutely necessary, but I would suggest removing it from the docs if it's not available.

I just ran into the same issue as @jakirkham.

**Comment by jreadey** [comment]
Release is now out on PyPi: https://pypi.python.org/pypi?%3Aaction=pkg_edit&name=h5pyd.
