### ISSUE TITLE
Raise errors on failures in loading data

### ISSUE THREAD

**Issue by jonrkarr** [HDFGroup/h5pyd#111]
`hsload` currently prints console messages when data loading fails (e.g., request entity too large): 

https://github.com/HDFGroup/h5pyd/blob/aa60cf5eb7bd960504e4916f29d3176d054a6522/h5pyd/_apps/utillib.py#L532

To make errors easier to detect, it would be helpful for `hsload` to exit with a non-zero exit code such as by calling `sys.exit(1)` after L532 above.

**Comment by jreadey** [comment]
Fix is in master.
