### ISSUE TITLE
hsload change dataset's datatype class from Compound (H5T_COMPOUND) to Opaque (H5T_OPAQUE)

### ISSUE THREAD

**Issue by trmt** [HDFGroup/h5pyd#127]
If compound dataset structure contains only one sequence member, hsload change dataset type to H5T_OPAQUE due to load.
Look like it happenes here  https://github.com/HDFGroup/h5pyd/blob/1bd5cf9ce4a8053ecd30e224604bcefc0e567f72/h5pyd/_hl/h5type.py#L395
cause len(dt) in that case returns 1
And after that dataset get his datatype here https://github.com/HDFGroup/h5pyd/blob/1bd5cf9ce4a8053ecd30e224604bcefc0e567f72/h5pyd/_hl/h5type.py#L462

Sry for my English, try to do my best

**Comment by jreadey** [comment]
This fix is now in master.

**Comment by jreadey** [comment]
Closing - fix is in the 0.12.0 release on PyPI.
