### ISSUE TITLE
PEP 632: Python 3.12 Incompatible with Distutils

### ISSUE THREAD

**Issue by ssolson** [HDFGroup/h5pyd#169]
Python 3.12.0 shipped Oct 2 2023. 

As per PEP 632 disutils no longer works with the latest stable version of python. 
https://peps.python.org/pep-0632/

Are there plans to address this incompatibility?

https://github.com/HDFGroup/h5pyd/blob/094f0b2b7e2a777f6dc1a6f60851cc856067d9a2/h5pyd/version.py#L15

**Comment by jreadey** [comment]
Yes I’m planning to get to this in the next few weeks.  Went through a similar excessive with the hsds setup
