### ISSUE TITLE
Add releases

### ISSUE THREAD

**Issue by grisaitis** [HDFGroup/h5pyd#20]
Even something preliminary, like release candidates or alpha or beta or whatever, would be useful. 

Reasons for:
- it's a prerequisite to https://github.com/HDFGroup/h5pyd/issues/11
- it's useful for maintaining dockerfiles that install this

**Comment by jreadey** [comment]
I'm planning to spend some time next week to clean up the code, then put out an alpha release.

Have you run into any issues that you'd like to see addressed immediately?

**Comment by grisaitis** [comment]
No issues :) just looking to use a release tag in my dockerfiles.

**Comment by jreadey** [comment]
I've belatedly started tagging releases I push out to PyPi.
Versions will be in the form 0.x.y  with x updated for major releases on y for minor fixes.
