### ISSUE TITLE
Fancy selections should check server version

### ISSUE THREAD

**Issue by mattjala** [HDFGroup/h5pyd#215]
Fancy selections should throw a useful error message about the HSDS server version if they're attempted with a server version that is too low. Right now, they'll get an error on HSDS's side and eventually time out.

**Comment by jreadey** [comment]
Don't older versions of HSDS throw a 400 error in this case?  From the users point of view that would seem as good as being told the operation wasn't supported based on the server version.

**Comment by mattjala** [comment]
> Don't older versions of HSDS throw a 400 error in this case? From the users point of view that would seem as good as being told the operation wasn't supported based on the server version.

The benefits of a specific message over the current behavior would be 1. faster (currently it has to time out) and 2. more helpful (user realizes they have to upgrade HSDS instead of e.g. looking for a mistake in their request)

**Comment by jreadey** [comment]
Did a test just now and it does seem like HSDS will time out.  That was unexpected!  But then I guess we are not as rigorous as we should be about catching malformed selection strings when the request is received.  
So yes checking that the server supports fancy selections would be good.

**Comment by jreadey** [comment]
Added version check in PR #223
