### ISSUE TITLE
pip install fails

### ISSUE THREAD

**Issue by swingingsimian** [HDFGroup/h5pyd#29]
Hi 
I am trying to get h5pyd up and running on the h5serv docker image available here:
 
    https://hub.docker.com/r/hdfgroup/h5serv/

Running the pip install command as documented gives the following:

```
# pip install h5pyd
Collecting h5pyd
  Could not find a version that satisfies the requirement h5pyd (from versions: )
No matching distribution found for h5pyd
```
This looks like it's trying to use versions from a local requirements.txt file, but it does not exist. Not quite sure whether this is a pip or h5pyd issue.

Thanks

**Comment by jreadey** [comment]
I haven't updated pypi for a while, but I'll look into the install issue as well as updating the contents.

Are you able to install by cloning from github and running setup?

**Comment by swingingsimian** [comment]
Yes, that worked fine for me.

**Comment by swingingsimian** [comment]
Incidentally, which is the official 'release' branch. Master is marked as
'stale' in github, but conversely 'develop' which is the default branch,
looks bleeding edge.

I went with 'develop', in the end which looks okay so far, barring some 403
teething problems.

**Comment by swingingsimian** [comment]
Post-email clarity strikes again, don't know why I didn't see the 2 release
tags. Disregard.

**Comment by jreadey** [comment]
I've switched h5pyd to use master as the default branch.  I figure with tags, there wasn't much benefit to having a separate dev and release branch.

Package is on PyPi now: https://pypi.python.org/pypi?%3Aaction=pkg_edit&name=h5pyd.

Let me know of any problems with the packaging.
