### ISSUE TITLE
FillValue no longer working 

### ISSUE THREAD

**Issue by rsignell-usgs** [HDFGroup/h5pyd#44]
I upgraded to the latest h5pyd, and now the fillvalues in my dataset are not working:
https://gist.github.com/rsignell-usgs/c3555fd60c391699197d53dcd0cb007c

The fill values in the original netcdf4 file were `1.0e37` but after writing with `h5load` the new `h5pyd` thinks the fillvalue is `0.0`.

This same notebook worked at the ESIP summer meeting.

**Comment by ajelenak-thg** [comment]
Would it be possible to get the original file?

My theory (without a shred of evidence) is that there is some confusion as to from where the fill value should come. `dset.fillvalue` gives the fill value from the HDF5 dataset's creation property list. And it's default value is `0.0`. What is the fill value you are referring to? The one stored in the dataset's `_FillValue` attribute?

**Comment by jreadey** [comment]
I have the source file - I'll investigate.

**Comment by jreadey** [comment]
I tried reloading the Sandy_ocean_his_nc4.nc file.  Looks like both the dataset.fillvalue and dataset _FillValue attribute are set to 1.0e37.

@rsignell-usgs - would you try loading the file again?  I think the files on jetstream got corrupted at some point.

**Comment by rsignell-usgs** [comment]
The fill values work as expected with this HSDS "file":
/home/rsignell/Sandy_ocean_his_nc4.nc   
but get returned as 0.0 with this "file":
/home/rsignell/Sandy_ocean_his_nc4c.nc

I created fresh versions of these today using "hsload".

**Comment by rsignell-usgs** [comment]
I wonder if it's a function of compression?

**Comment by jreadey** [comment]
I think this should be fixed with the commit in issue #119.  
Please re-open if you are still seeing this.
