### ISSUE TITLE
mode ='r'  seems to have no effect

### ISSUE THREAD

**Issue by mikejiang** [HDFGroup/h5pyd#46]
```python
f_remote = h5pyd.File(domain, "r")
ds_remote = f_remote["/data"]
```
`ds_remote` is still writable and I've verified it by `f_remote.close()` and reopening it.

**Comment by jreadey** [comment]
This should be fixed in this commit: https://github.com/HDFGroup/h5pyd/commit/2dee27358c74e0e646d57b9d8b333b2f1632da31.
