### ISSUE TITLE
hsls , but hsdel ?

### ISSUE THREAD

**Issue by rsignell-usgs** [HDFGroup/h5pyd#49]
This is just a minor annoyance, but thought I'd mention it anyway:

Why Linux style `hsls`, but Windows style `hsdel`?

Would have thought Linux like: `hsls` and `hsrm` 
or Windows like: `hsdir` and `hsdel`
or would be more consistent...

**Comment by jreadey** [comment]
To keep both Windows and Linux types happy, I've aliased hsrm to hsdel.
i.e. ``$hsrm`` and ``$hsdel`` will invoke the same script.
