### ISSUE TITLE
Support ACL ops

### ISSUE THREAD

**Issue by jreadey** [HDFGroup/h5pyd#6]
Add support for ACL operations.

**Comment by ahalota** [comment]
If this isn't available right now, does that mean I won't be able to edit a file that requires authentication to POST?

**Comment by jreadey** [comment]
I can cook up something to get you started -- say read username & password from environment variables and pass that in the auth header of each request.

Can you try it out on a non-secure h5serv instance and see if there are any problems with the h5pyd functionality?

**Comment by ahalota** [comment]
Sure, I'll do a test on my local non-secure h5serv instance in the next 2 hours and let you know how it goes.

**Comment by jreadey** [comment]
ACL ops are implemented in this commit: https://github.com/HDFGroup/h5pyd/commit/45db3f4a9f58d58b6aa0e7909e3977f4e999ca1d.

@ahalota - can you try this out and let me know if you see any problems.

Take a look at test_file.py, test_auth() to see how to use ACLs.  (Also this section in the h5serv docs is helpful: http://h5serv.readthedocs.io/en/latest/AclOps/index.html)
