### ISSUE TITLE
h5pyd._hl.folders.Folder.__repr__() and .domain fail on root folder

### ISSUE THREAD

**Issue by JacobDuckett** [HDFGroup/h5pyd#72]
`Folder.__repr__()` and `Folder.domain` fail with the same error that arises from similar lines of code:
```python
self._domain + '/'
```

In the case of the root server folder, `self._domain` is set to `None` on line 114, causing either of the above methods to throw a TypeError.

**Comment by jreadey** [comment]
@JacobDuckett's PR (https://github.com/HDFGroup/h5pyd/commit/38e758564ab4bea1a313f7fac4ec054917b82d40) resolves this.
