### ISSUE TITLE
Open ExternalLinks with current credentials

### ISSUE THREAD

**Issue by jjaraalm** [HDFGroup/h5pyd#79]
`ExternalLinks` are opened without any credentials passed in which requires `default` read ACLs to be set. Stored credentials (and possibly access mode) should be forwarded on.

**Comment by jreadey** [comment]
I've checked in the code above.  Let me know if that works for you.  I wasn't sure if external links are a problem with OpenID authentication, but this should work at least when credentials are passed in the File init arguments.

**Comment by jreadey** [comment]
Closing this - please re-open if it's still an issue.
