### ISSUE TITLE
create_group clears file

### ISSUE THREAD

**Issue by ahalota** [HDFGroup/h5pyd#8]
I ran the following code on my file. The new group gets added, however all of the old data in the file disappears. The file size is now 8kb from previous 50mb, so it definitely got wiped.

```
fileOut = h5py.File("My_File.hdfgroup.org","w")
fileOut.create_group('2015')
```

This is a file that previously had ACL authentication, which I removed. Before removing it I got an IOError and no changes were made to the file.

**Comment by jreadey** [comment]
Yes, that's expected. :)

 In h5py as well, using the 'w' mode deletes any existing content in the file.  You'll want to use 'a'.

**Comment by jreadey** [comment]
Closing this as it is not a problem with the package.
