### ISSUE TITLE
hsget: unexpected keyword argument

### ISSUE THREAD

**Issue by seb5g** [HDFGroup/h5pyd#83]
Hello, trying to load data from hsds to a local h5file using hsget. hsget makes a call to the utility function load_file but with a keyword argument not recognised by this method:
In hsget.py:
`load_file(fin, fout, verbose=verbose, nodata=nodata)
`
while in load_data signature:
`def load_file(fin, fout, verbose=False, dataload="ingest", s3path=None, deflate=None,):`

I guess the nodata has something to do with the dataload arg but didn't dig too deep!
h5pyd version: 0.7.1

**Comment by seb5g** [comment]
actually this issue is very close to #80

**Comment by jreadey** [comment]
Thanks for the pointer -- the above commit should fix the problem.
