### ISSUE TITLE
IOError "Bad Request: invalid linkname, '/' not allowed" for create_dataset

### ISSUE THREAD

**Issue by ahalota** [HDFGroup/h5pyd#9]
My input dataset does not yet have a group called 2015. I am not able to create a dataset inside of it. In h5py, I was able to do so without first creating the dataset.

`fileOut.create_dataset('2015/newdset',data=newdata,compression='gzip')
`

```
  File "...\h5pyd\_hl\group.py", line 148, in create_dataset
    self[name] = dset
  File "...\h5pyd\_hl\group.py", line 420, in __setitem__
    self.PUT(req, body=body)
  File "...\h5pyd\_hl\base.py", line 418, in PUT
    raise IOError(rsp.reason)
IOError: Bad Request: invalid linkname, '/' not allowed
```

**Comment by ahalota** [comment]
Hm. I checked again after creating the dataset individually first, and am still experiencing this issue. The issue was NOT the nonexistent group, but something else.
Below the exact name I used:

` c_fore = fileOut.create_dataset("2015/C_FORE",data=FORE_emissions, compression="gzip")`

**Comment by jreadey** [comment]
Ok, that's a bug.  As a work-around use the handler of the group you created for the create_dataset call.  i.e. 2015_grp.create_dataset(...)

**Comment by ahalota** [comment]
Works with the workaround.

**Comment by jreadey** [comment]
This should be fixed with the checkin above.
